### ISSUE TITLE
Dataset for reproducing results

### ISSUE THREAD

**Issue by almaan** [huBioinfo/CytoCommunity#5]
Hi there,

really cool package and congratulations on the publication. 

Some people in my team are really interested in trying to reproduce some of your results, especially on the CODEX spleen dataset. Looking through your "Data Availability Statement" in the publication I noticed how you refer to the original data repository, however, I could not find the compartment annotations here (e.g., "Red Pulp", "Marginal Zone" etc.). 

Would it be possible for you to share the data with the cell type and compartment annotations, perhaps as an `.h5ad` object or something similar. I'm assuming you used something like this to run your method and evaluate your results.

Best,
Alma

**Comment by huBioinfo** [comment]
Hi Alma,

Please see the "CODEX_SpleenDataset.zip" we just appended to the main branch. It includes spatial location, cell type and compartment annoations of all cells for the three healthy spleen samples used in our study. It was provided by the original study authors.

Best,
Yuxuan

**Comment by almaan** [comment]
This is great, thank you so much, I really appreciate the swift response!
