### ISSUE TITLE
supervised method

### ISSUE THREAD

**Issue by Elena983** [huBioinfo/CytoCommunity#6]
Hi

I would like to generate the heatmap as in your paper
Could you please share the code or ideas?

Also, I cannot find where to get the file '..._GraphLabel.txt.'

Thank you!

**Comment by huBioinfo** [comment]
Hi, 
Please see the "CellTypeEnrichmentAnalysis.zip" just uploaded to the master branch.
It includes example Matlab scripts for cell type enrichment analysis of the identified TCNs by unsupervised CytoCommunity.
You can put it in the same directory with the folders Step1/2/3/4_Output. Just modify the hyperparameters in the gen_CellTypeEnrichmentMatrix.m and run it. You can obtain a CellTypeEnrichment_Res.mat file, which includes a matrix named "CellTypeByTCN_EnrichScoreMatrix" with rows representing cell types same as in the "/Step1_Output/UniqueCellTypeList.txt" and columns representing TCNs from TCN-1 to TCN-M. The value in the matrix is -log10(hypergeometric test p-value). This script can be easily adapted to analyzing results of the supervised version.

**Comment by Elena983** [comment]
Thank you

Please explain how to get the additional file for the supervised approach.

**Comment by huBioinfo** [comment]
Additional "**_GraphLabel.txt" files are prepared based on your dataset. For example, if your dataset includes samples of two conditions, you can put an integer "0" in the "GraphLabel.txt" of the samples of condition-1 and an integer "1" for the samples of condition-2. Example files can be found under the directory "Tutorial/Supervised/MIBI-TNBC_Input/".
